### ISSUE TITLE
🐛 [BUG] - Warm-up sets, dropsets and sets to failure sets not included in Volume statistics charts

### ISSUE THREAD

**Issue by TheSecondWing** [madmustachecompany/Blast-Workout-App#68]
### Description

Hello,

I found out that warm-up sets, dropsets and sets to failure are not included in the total Volume statistics charts of a given exercise.
For example, here are 5 sets for a given bench press exercise:

- Warm-up set: 10x 20kg
- Normal set: 12x 30kg
- Drop set: 5x 50kg
- Drop set: 4x 40kg
- Set to failure: 8x 30kg

That should be a total of 1210kg lifted and logged in the Volum statistics chart.
But it only registers 360kg, which corresponds to the Normal set only.

This seems like a bug and is misleading I think.
Every sets should be included in the total Volume lifted, not only Normal sets.

Thanks.

### Reproduction steps

```bash
1. Go to a given session
2. Input set as warm-up, dropset or set to failure
3. Go to exercise log
4. Go to Volume statistics chart
5. Weight lifted during a warm-up set, dropset or set to failure is not included
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### OS

Android

**Comment by madmustachecompany** [comment]
@TheSecondWing Thanks for reporting this issue. 
It has been fixed and should be available in the next released, after a short period of testing 👌

**Comment by TheSecondWing** [comment]
Thanks a lot!

**Comment by TheSecondWing** [comment]
Hello @madmustachecompany,

I just downloaded the 1.61 version and checked the volume historic of my exercises.

Dropsets and sets to failure now seem to be taken into account for the volume statistics charts.

However, the warm-up sets are still not included.

Best regards.

**Comment by TheSecondWing** [comment]
Example:

Here it should be a total volume lifted of 1800 (10 x 20 **+** 4 x 10 x 40).

But it registered as 1600 (without the 10 x 20 warm-up).

![IMG_20240130_085123.jpg](https://github.com/madmustachecompany/Blast-Workout-App/assets/156791196/b7fb4e9c-bb76-4973-88a9-19d78e2b3351)

![IMG_20240130_085147.jpg](https://github.com/madmustachecompany/Blast-Workout-App/assets/156791196/1c8caf57-0ace-46b5-926f-6d0c3528d31f)

**Comment by madmustachecompany** [comment]
Yes, this is deliberate :)
It is generally accepted that warm-up series shouldn’t be counted towards actual working volume.
Although this isn't a universal rule, we've chosen this option because it also provides greater flexibility. Depending on whether or not you want to count them in your total volume, you can still include them in your total volume by saving them as normal sets.
Hopefully this makes sense.

**Comment by madmustachecompany** [comment]
This is also why they are shown in grey in the history.

**Comment by TheSecondWing** [comment]
> This is also why they are shown in grey in the history.

Alright, makes sense. Thanks for the answer!

As long as Dropsets and Failure sets are included, that's the most important.

Ticket can be closed if everything's OK for you. Thanks a lot!
